<?php

namespace App\Form\WidgetType;

use App\Entity\Widget;
use App\Enum\FicheModeEnum;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RadioType extends AbstractWidgetType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['mode'] === FicheModeEnum::SEARCH) {
            $this->buildSearchForm($builder, $options);
        }
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        /**
         * @var Widget $widget
         */
        $widget = $options['widget'];

        $choicesKey = array_map(function($value){
            return hash('sha256', (string)$value);
        }, $widget->getChoices());

        $choices = array_combine($choicesKey, $widget->getChoices());

        $view->vars['expanded'] = $options['expanded'];
        $view->vars['multiple'] = $options['multiple'];
        $view->vars['placeholder'] = '';
        $view->vars['preferred_choices'] = [];
        $view->vars['choices'] = $choices;
    }

    public function getBlockPrefix()
    {
        return 'fichit_radio';
    }

    private function buildSearchForm(FormBuilderInterface $builder, array $options)
    {

    }

    protected function getSearchCriterias(): array
    {
        return [
        ];
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefault('expanded', false);
        $resolver->setDefault('multiple', false);
    }
}