twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        picturesDir: '%picturePublicUploadDir%/'
        areaMinSize: '%areaMinSize%'
        areaMaxSize: '%areaMaxSize%'

        textAlignPositions: '@App\Enum\TextAlignPositionEnum'

    form_themes:
        - 'form/TWIG_widget_types.html.twig'
